import localFont from 'next/font/local';
import Header from './components/Header/Header';
import Providers from './providers';
import ProtectedRoutes from './components/ProtectedRoutes/index';
import './globals.css';
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Bolg Posts',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <ProtectedRoutes>{children}</ProtectedRoutes>
        </Providers>
      </body>
    </html>
  );
}
